app = "bestseat"
primary_region = "sea"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 8000

  [[services.checks]]
    type = "http"
    interval = "10s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/healthz"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1