"""initial migration

Revision ID: c43746168412
Revises: 
Create Date: 2025-06-06 13:37:48.464919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c43746168412'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE screens ALTER COLUMN layout_json TYPE JSON USING layout_json::json")
    op.alter_column('theaters', 'screens_count_source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('theaters', 'screens_count_source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.execute("ALTER TABLE screens ALTER COLUMN layout_json TYPE VARCHAR USING layout_json::text")
    # ### end Alembic commands ###