"""Add name column to screens

Revision ID: d9ceb17695ba
Revises: 95429cbd38a7
Create Date: 2025-06-07 10:56:05.253956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ceb17695ba'
down_revision: Union[str, None] = '95429cbd38a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screens', sa.Column('name', sa.String(), nullable=True))
    op.add_column('screens', sa.Column('is_imax', sa.Boolean(), nullable=True))
    op.add_column('screens', sa.Column('best_seat', sa.String(), nullable=True))
    op.add_column('screens', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('theaters', 'osm_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('theaters', 'osm_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('screens', 'notes')
    op.drop_column('screens', 'best_seat')
    op.drop_column('screens', 'is_imax')
    op.drop_column('screens', 'name')
    # ### end Alembic commands ###
